name: swoole run main
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
jobs:
  job1:
    uses: ./.github/workflows/share.yml
    secrets: 
      ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      CYM_TOKEN: ${{secrets.CYM_TOKEN}}
