name: swoole run swoole-cli-amdx86
on:
  workflow_dispatch:
    inputs:
          php_version:
            description: '要构建的php版本号 (例如: 8.1.14)'
            required: true
            default: '8.1.14'
            type: string
          swoole_version:
            description: '要构建的swoole版本号 (例如: v6.1.1)'
            required: true
            default: 'v6.1.2'
            type: string
  # push:
  #   branches: [ "main" ]
jobs:
  job1:
    uses: ./.github/workflows/share.yml
    with:
        runs-on: ubuntu-latest
    secrets: 
      ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      CYM_TOKEN: ${{secrets.CYM_TOKEN}}
