name: swoole run swoole-cli-arm
on:
  workflow_dispatch:
    inputs:
        php_version:
          description: '要构建的php版本号 (例如: 8.1.14)'
          required: true
          default: '8.1.14'
          type: string
        swoole_version:
          description: '要构建的swoole版本号 (例如: 6.1.1)'
          required: true
          default: '6.1.1'
          type: string
  # push:
  #   branches: [ "main" ]
jobs:
  job1:
    uses: ./.github/workflows/share.yml
    with:
        runs-on: ubuntu-24.04-arm
    secrets: 
      ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      CYM_TOKEN: ${{secrets.CYM_TOKEN}}
