name: swoole run swoole-cli-arm
on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
jobs:
  job1:
    uses: ./.github/workflows/share.yml
    with:
        runs-on: ubuntu-24.04-arm
    secrets: 
      ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      CYM_TOKEN: ${{secrets.CYM_TOKEN}}
